import type { Metadata } from "next";
import { Courier_Prime, PT_Sans } from "next/font/google";
import NavBar from "@/app/components/layout/Navbar";
import "./globals.css";

const courierPrime = Courier_Prime({
  weight: ['400', '700'],
  subsets: ['latin'],
  variable: '--font-courier-prime',
})

const ptSans = PT_Sans({
  weight: ['400', '700'],
  subsets: ['latin'],
  variable: '--font-pt-sans',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${courierPrime.variable} ${ptSans.variable}`}>
      <body>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
